apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: waddProg/vwn_address
      context: ./services/address
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: waddprog/vwn_auth
    #   context: ./services/auth
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: waddprog/vwn_mailer
    #   context: ./services/mailer
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .


