apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: storm-wall-444412-i5
  tagPolicy:
    gitCommit: {}
  artifacts:
    # - image: us.gcr.io/storm-wall-444412-i5/address
    - image: waddprog/vwn_address
      context: ./services/address
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: us.gcr.io/storm-wall-444412-i5/auth
    - image: waddprog/vwn_auth
      context: ./services/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: us.gcr.io/storm-wall-444412-i5/mailer
    - image: waddprog/vwn_mailer
      context: ./services/mailer
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: waddprog/vwn_connection
      context: ./services/conection
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: waddprog/vwn_post
      context: ./services/post
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .


