apiVersion: batch/v1
kind: Job
metadata:
  name: address-db-migration
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: address-db-migration
          image: waddprog/vwn_address
          # command: ["npx", "sequelize-cli", "db:migrate"]
          command: ["sh","-c"]
          args: 
            - >
              echo "Database is ready. Running migrations...";
              node node_modules/.bin/sequelize db:migrate &&
              echo "Migration completed starting seeding" &&
              node node_modules/.bin/sequelize db:seed:all &&
              echo "Seeding completed"
          env:
            - name: NODE_ENV
              value: "development"
            - name: DB_HOST
              value: "address-posgres-srv" 
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "address"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
          imagePullPolicy: Never
      restartPolicy: Never
