apiVersion: apps/v1
kind: Deployment
metadata:
  name: connection-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connection
  template:
    metadata:
      labels:
        app: connection
    spec:
      containers:
        - name: connection
          image: us.gcr.io/storm-wall-444412-i5/vwn_connection
          # image: waddprog/vwn_connection
          # imagePullPolicy: Never
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          # resources:
          #   limits:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: connection-srv
spec:
  selector:
    app: connection
  ports:
    - name: connection
      protocol: TCP
      port: 3000
      targetPort: 3000
