apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post
          image: us.gcr.io/storm-wall-444412-i5/vwn_post
          # image: waddprog/vwn_post
          # imagePullPolicy: Never
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name : CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secret-api-key
                  key: CLOUDINARY_API_KEY
            - name : CLOUDINARY_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudinary-api-secret
                  key: CLOUDINARY_API_SECRET
            - name : CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-cloud-name
                  key: CLOUDINARY_CLOUD_NAME
          # resources:
          #   limits:
          #     memory: "256Mi"
          #     cpu: "500m"
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: post-srv
spec:
  selector:
    app: post
  ports:
    - name: post
      protocol: TCP
      port: 3000
      targetPort: 3000
