name: tests-forum

on:
  pull_request:
    paths:
      - 'services/forum/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd services/forum && npm install && npm run test:ci
